<?php
$words = [
    'Unable to login. Check your login information and try again.',
    'Use the {site_name} to get orders to customer',
    'Let customer {transaction_type} their orders to get more sales at a low fee',
    'Let customer {transaction_type} at your restaurant at low fee',
    'All Restaurant',
    'New Restaurant',
    'Popular',
    'Best Seller',
    'Recommended',
    'Points earned on order #{order_id}',
    'First order earn points',
    'Earn points by registering',
    'Truck','Car','Bike','Bicycle','Scooter','Walk',
    'Total Orders','Total Cancel','Total refund','Total Sales',
    'Percentage','Fixed','Privacy Policy','Terms and condition','About us',
    'Schedule for later','Schedule','Now','Create new order',
    'Your order contains items from {restaurant_name}. Create a new order to add items.',
    'Page not found',
    "uh-oh! Looks like the page you are trying to access, doesn't exist. Please start afresh",
    'Asap',
    'This month you got {{count}} New Reviews',
    'Total Sales','Delivery Fee','Total Tax','Total Tips','Sales this week',
    'Earning this week','Your balance',
    'Unlimited for all user','Use only once',
    'Once per user','Once for new user first order','Custom limit per user','Only to selected customer',
    'Restaurant','Food','Restaurant featured',
    'Table information','Guest','Room name','Table name','Bookings',
    'Points','Notifications Settings','Enabled','Communication preferences',
    "Select only the marketing messages you would like to receive from {{settings.site_name}}. You will still receive transactional emails including but not limited to information about your account and certain other updates such as those related to safety and privacy.",
    'Submit',
    'Member since {{date_created}}',
    'Migration Tools',
    'Instructions',
    'Export Tables from Old Database',
    'Use PhpMyAdmin to export the following tables:',
    'If the table is large, consider using the mysqldump command for faster data exporting.',
    'Import Tables into New Database',
    'Utilize either PhpMyAdmin or the MySQL command to import the tables.',
    'Warning: Clean Database Table',
    'Before importing, ensure that the target database table is clean, as the existing data will be deleted during the import process.',
    'Select Data for Import',
    'Below, choose the data to import and input your old table prefix (e.g., mt).',
    'Click "Submit."',
    'Continue Sequential Import',
    'Import the selected data in sequence until you have completed the import process.',
    'Select Data to import',
    'Select',
    'Table Prefix',
    'The table prefix for your old tables',
    'Order #{{order_id}}',
    '{count} Items for {first_name}',
    'Member since {{date_created}}',
    'This month you got {{count}} New Reviews',
    "You're saving {{discount}}",
    '({{coupon_name}}) {{amount}}% off',
    'Min. spend {{amount}}',
    '{{amount}}% off over {{order_over}} on {{transaction}}',
    'valid {{from}} to {{to}}',
    'All','Processing','Ready','Completed',
    'Check out the {restaurant_name} delivery order with {website_title}',
    'Find Your Perfect Bite','Search foods and restaurants',
    'Clear','Search','Looking for Best Sellers food near your area?',
    'See our recommended food for today','Restaurants',
    'Foods','No data available','Forgot Password','Reset Password',
    'Have an account',"You're saving {{discount}}",
    '{offer_amount} off w/ code {discount_name}',
    '{offer_amount} off min. {min_order}',
    'Orders as of today {{date}}',
    'No results for',
    'Create new order',
    'Your order contains items from {restaurant_name}. Create a new order to add items.',
    'Driver',
    'Schedule',
    '0 Result(s)',
    'No available restaurant with your selected filters',
    'I have read and agree to {{site_name}} Auto Renewal Terms, {{terms}}Terms of Service{{end_terms}} and {{cancellation}}Cancellation Policy{{end_cancellation}} and acknowledge receipt of the {{privacy}}Privacy Notice{{end_privacy}}',
    'Minimum order for this voucher is [min_order]',
    'Digital Wallet','Available Balance','Add Funds',
    'Refunds','Top-ups','Cashbacks','Adjustment',
    'Live Chat','No chats selected','Search restaurants',
    'Chats','Order#','Search for','No matching records found',
    'is typing','Uknown','Please wait...','Your message',
    'Receive a {{amount}} bonus credit on all top-ups of {{minimum_amount}} or more.',
    'Valid for top-ups made between {{start}} and {{end}}',
    'Add Funds to Your Wallet',
    'Please note that for top-up transactions, only online payment methods are currently supported.',
    'Kindly select an online payment option to proceed.',
    'Payment Method','Change',
    "We noticed you haven't added a default payment method yet.",
    'To proceed with your transaction smoothly, please add a payment online method to your account. Thank you!',
    'Click here to add online payment',
    'Add Funds',
    'Please ensure that the entered payment amount is correct and matches your intended top-up value.',
    'Make sure to enter any promo codes accurately to avail of bonuses or discounts.',
    'Funds added to your wallet are non-refundable.',
    'Congratulations!',
    'Your digital wallet has been successfully loaded.',
    'Transaction Details!','Amount Loaded','Date and Time','Close',
    'No data available','Transaction ID','Open until {ends}','+{rating} ratings',
    'Summary','Order#','Place on','Order Total','Delivery Date/Time','DELIVERY ADDRESS',
    'ITEMS ORDERED','QTY','PRICE','Contact Us','Information','Check out the {restaurant_name} delivery order with {website_title}',
    '{{website_title}} needs to be contact you for more information. You can expect a phone call or email in 1-3 business days',
    'Check {{email_address}} for an email to reset your password.',
    '{{count}} store','{{count}} stores','miles','km','Ratings','Open until {ends}','{{distance} {{unit}} away','{{distance} {{unit}}',
    "Few words about {{restaurant_name}}",'Reviews','We sent a code to {{email_address}}.','Paid by [payment_name]',
    'Place on {{date}}','Paid on [date]','Sub total ({{count}} items)','{{tax_name}} {{tax}}%',
    '{{tax_name}} ({{tax}}% included)',"I authorise {website_name} to send instructions to the financial institution that issued my card to take payments from my card account in accordance with the terms of my agreement with {website_name}",
    'We sent your order to {{restaurant_name}} for final confirmation.',
    'Preparing your order','Payment by {{payment_name}}','{{count}} store','{{count}} stores',
    '{{points}} Points','Get {amount} off for every {points} points','Your available balance is {points} points.',
    'Redeem {max} out of {points} points','Discount Applied: {amount} off using {points} points.','Not now','Global points',
    'Order #{{order_id}} Successfully Placed with Wallet',
    'Redeem {points} points to order #{order_id}',
    'First order earn points',
    'Commission on order #{{order_id}}',
    'Funds Added via {payment_name}',
    'Earn points by registering','Pending','Confirmed','Cancelled','Denied','No show','Wait list','Finished',
    'Looks like this order is higher than your digital wallet credit.',
    'Please select a payment method below to cover the remaining amount.',
    'This order will earn you {points} points upon completion!',
    'This order will earns you {points} points!',
    'This order will earns {points} points!',
    'Opens [day] at [time]',
    'You can login to merchant portal by clicking {{start_link}}here{{end_link}}',
    'Top-up amount should meet the minimum requirement of {{topup_minimum}} for a successful transaction. The maximum allowed is {{topup_maximum}}.',
    'Top-up amount exceeds the maximum limit of {{topup_maximum}} for a single transaction. The minimum required is {{topup_minimum}}.',
    'Congratulations','his order will earn you {points} points upon completion!',
    'Paid by {payment_name}','Payment by {payment_name}','Paid on {date}','Order #{order_id}','{n} item|{n} items',
    'Please enter a new password for your account, [first_name]',
    'takeout','dinein','pickup','delivery','Queue','In progress','Ready','Delayed','Cancelled','Completed',
    '{n} open order|{n} open orders','{n} scheduled order|{n} scheduled orders','Login Succesful',
    'Email address not found','Line items status updated','No items available','Kitchen order not found',
    'No available data','{n} open order|{n} open orders','Record not found','Your request to delete your account has been submitted',
    'Invalid verification code','User not login or session has expired','New Canncelled Alert','There is a new cancelled order with order# {order_reference}.',
    'Order already exist in kitchen table','Walk-in Customer',
    'Hold','Table','Request','Search customer name','No items added','Customer','Promo','Discount','Tips','Points','Skip Kitchen','Kitchen',
    'Proceed to pay','Reset','Hold Bill','Total','available','pending','Customer succesfully created','Go with merchant recommendation',
    'No default map provider, check your settings.','Address saved succesfully','Discount {{discount}}%','Discount cannot apply due to sub total is less than 1',
    'Discount must be greater than zero','Voucher code not found','Tip are disabled','Tips must be greater than zero',
    'Maximum points for redemption: {points} points.','Discount cannot be applied due to total less than zero after discount',
    'Points apply to cart','Total amount succesfully added','Order reference is required','Order successfully hold',
    'This store is close right now, but you can schedulean order later.','Your payment has been successfully processed,and your order #{order_id} is complete.',
    'Your Order has been place',"You don't have current orders.",'Please select Now or to Schedule for later','Invalid date',
    'Invalid time','Your order has been successfully sent to kitchen.','Cart details not found','Order updated','Receipt Sent Successfully',
    'Invalid request id','Request succesfully sent to printer','In Progress','Order History','All',
    '{n} item|{n} item(s)','Select your currency','Already have an account?','Login here','Please select','Choose your services',
    'Flexible','Pricing','for Every','Restaurant','Transparent pricing. No hidden costs. Advanced features to elevate your business',
    'Choose Plan','Select Payment','Method','Subscribe','District/Area','No matching data','City','State','Postal Code/Zip Code','Search Restaurants',
    'Choose your location','Your favorite cuisines','Popular Restaurants Near You','New Restaurants',
    'Join Our Network of Restaurants','Discover the advantages of partnering with us and see how we can help your business grow.',
    'Order Your Favorite Dishes Online!','Enjoy a seamless food ordering experience with fast delivery from your favorite local restaurants.',
    'Join as a delivery person!','Start earning extra income by delivering to homes. Enjoy top rates and great benefits as part of our team.',
    'Register now!','Signup now','{total} Restaurants found','{estimated} mins','House number','Street','Street Number','State/Region',
    'City','Distric/Area/neighborhood','Zip Code','Location Name','To ensure accurate and timely delivery, we need the latitude and longitude of your delivery address. This helps us pinpoint your exact location and avoid any delivery delays',
    'To ensure accurate and timely delivery, we need the latitude and longitude of your delivery address. This helps us pinpoint your exact location and avoid any delivery delays',
    'You can easily find your coordinates by visiting','Latitude','Longitude','Delivery options','Add delivery instructions',
    'eg. ring the bell after dropoff, leave next to the porch, call upon arrival, etc','Succesful','Succesfully updated','Restaurants',
    'Filters','Clear all','Quick filters','Offers','Cuisines','No results found for','Show less','Show more','Price','No more items to display',
    'No Restaurants found',"We couldn't find any results with the current filters. Try changing the filters or reset them to explore more options.",
    'Search for restaurants, cuisines,and dishes','Search for','Recent searches','Popular searches','Filters','Apply',
    'Ratings 4+','Best Seller','Accept vouchers','Deals','Search Cuisine','Choose an address','Add or choose an address','Add Address',
    'Add {amount} to Get Free Delivery!','Are you sure to delete this?','Yes','Save Address','View Saved Addresses',
    'Search Booking','Total Bookings','You must be at least 18 years old to enter this section.','Please confirm your age.',
    'Over 18','Under 18','Promotions','Enjoy discounts on items','See details','Get {offer_amount} off with {discount_name}! Cap: {max_discount_cap}, Min: {min_order}. Offer expires on {valid_to}',
    'Enjoy {offer_amount} off with {discount_name}! Min {min_order}, Max {max_order}. Offer expires on {valid_to}','Use coupon code {discount_name} to get {offer_amount} off your order. Valid for orders between {min_order} and {max_order}. Maximum discount: {max_discount_cap}. Offer expires on {valid_to}',
    'Use coupon code {discount_name} to get {offer_amount} off your order. Valid for orders between {min_order} and {max_order}. Offer expires on {valid_to}',
    'Get {offer_amount}% off! orders over {max_order}, Max savings: {max_discount_cap} on {transaction_type}. Offer valid until {valid_to}',
    '{offer_amount}% off orders over {max_order}! Offer valid until {valid_to}','No available promos','Open until {ends}','+{rating} ratings',
    'Become our delivery partner','Get paid to deliver','Complete address',"Enter verification code we've sent on given number",'Resend','Enter verification code',
    'We need your driving license information','Enter your license correctly','License number','License expiration  (YYYY/mm/dd)','License front photo','License back photo',
    'There is a new scheduled order with order# {order_reference}.','There is a new order awaiting acknowledgment with order# {order_reference}.',
    'There is a new scheduled order move to current with order# {order_reference}.','Order reference #{order_reference} is updated by kitchen','View',
    'Walk-in Customer','from {lowest_price}','Read less','Read More','Pay Subscriptions',"Hello! You've got a new message from {first_name}",
    'fee per order','fixed order fee','Order from your favorite restaurants & track on the go, with the all-new K app.',
    'In your pocket','Distance','Top-rated','Minimum Spend: {amount}','{amount}% off over {max_order}','Maximum Spend: {amount}','Maximum Discount Cap: {amount}',
    'Valid Until: {date}','Applicable to {transaction_type}','({coupon_name}) {amount}% off','Booking ID #{reservation_id}','{n} person|{n} persons',
    'Your reservation successfully updated.','Invalid merchant UUID','Invalid reservation id','Reservation id not found','Reservation cancellation failed, status is not anymore pending',
    'Your reservation ID {reservation_id} has been cancelled','Reservation id is missing','Invalid merchant id','Please select room','Please select table','Reservation ID: {reservation_id}',
    'Your reservation successfully updated.','Invalid reservation date','Invalid reservation time',"You've earned {points} points",'Paid by Digital Wallet',
    '+{points} points','{item_name} is not available','Open {open} - {end}','{n} rating|{n} ratings','Schedule','{distance} away','Distance {distance}','{estimation} mins',
    'Your available points {balance}','{discount} Off','{points} more points needed','Valid Until: {{date}}','({{coupon_name}}) {{amount}} off','Maximum Spend: {max_order}',
    'Maximum Discount Cap: {max_discount_cap}','{amount} off using {points} points.','{amount} off','{{points}} Points','{points} Off','less voucher',
    'Rate Your {restaurant_name} Experience!','You already added review for this order','Review has been added. Thank you.',
    'An OTP has been sent to your email address {{email_address}}','An OTP has been sent to your phone number {{mobile_number}}',"We couldn't find any account associated with the provided phone number.",
    'This is pickup',"Remember to collect your food at the restaurant when it's ready.",'This is dinein','Remember to go to restaurant address.',
    'You will be notified when order is ready.','Add {required_subtotal} to unlock this free item','You unlocked {qty} free item!','Free!'
];

// endx