<?php
$words = [
    'Ordering & Food',
    'Food default avatar',
    'Select image',
    'User default avatar',
    'Merchant default avatar',
    'Add menu items',
    'Select a menu to edit or',
    'create new menu',
    'Pages',
    'Custom links',
    'Menu structure','Delete Confirmation',
    'Are you sure you want to permanently delete the selected item?',
    'Cancel','Delete',
    'Drag the items into the order you prefer.',
    'Menu name','Save menu','Add to menu','Update words',
    'Communication',
    'Chats',
    'Enabled chat','Enabled chat deletion','Search for',
    'View Profile','Delete chat','No matching records found',
    'is typing','Order#','Uknown','Please wait...',
    'No chats selected','Your message','Digital Wallet',
    'Bonus Funds','Digital Wallet','Top-Up',
    'Refund to Wallet','Enabled Top-Up','Minimum top-up amount',
    'Maximum top-up amount','Transaction Limits','Spending amount limit',
    'Bonus Funds','Digital Wallet Transactions',
    'Min. Amount','Multi Currency','Exchange Rates',
    'Search customer or merchant','Chat Settings','Merchant',
    'Migration Tools',
    'Instructions',
    'Export Tables from Old Database',
    'Use PhpMyAdmin to export the following tables:',
    'If the table is large, consider using the mysqldump command for faster data exporting.',
    'Import Tables into New Database',
    'Utilize either PhpMyAdmin or the MySQL command to import the tables.',
    'Warning: Clean Database Table',
    'Before importing, ensure that the target database table is clean, as the existing data will be deleted during the import process.',
    'Select Data for Import',
    'Below, choose the data to import and input your old table prefix (e.g., mt).',
    'Click "Submit."',
    'Continue Sequential Import',
    'Import the selected data in sequence until you have completed the import process.',
    'Upload Images to New Server',
    'Transfer all images from the /upload folder in your old server to the corresponding /upload folder in your new server.',
    'Select Data to import',
    'Select',
    'Table Prefix',
    'The table prefix for your old tables',
    'Update front language words',
    'Update backend words',
    'Utilities','Change new order status','Merchant APP','Loyalty Points',
    'This cron job automates the process of updating order statuses within the system, ensuring timely and accurate changes in the order lifecycle based on predefined criteria or time triggers.',
    'Automates order assignment in the driver app and calculates rider earnings, streamlining the allocation process and ensuring accurate compensation based on completed deliveries.',
    'This cron job automates the process of setting points to expire at the year-end, ensuring the timely management of expiring points within the system.',
    'run every (1)minute',
    'run every (2)minute',
    'run every (2)minute or (5)minute',
    'run every (5)minute',
    'Automated alerts for new orders; ensures continuous notifications to the merchant app, enabling prompt action and order processing.',
    'run at before end of the year','Note','Link',
    'Click here how to run cron jobs',
    'Invoice','Table reservation','Allergens','Reservation list','Order Type',
    'Rejection List','Pause Order list','Status Actions','Tip List','Booking Cancellation','Cookie Preferences','Vehicle maker',
    'Delivery Order Help','Delivery Decline Reason','Marketing','SMS','Delivery Management',
    'Mobile Merchant','Printers','Addon manager','Fixed database','Clean database','Cron Jobs','New signup',
    'Plan List','Order Settings','Bank Deposit','Pay on delivery','Invoice List','Bank Deposit','Invoice Settings',
    'Payment change','Order currency','Base currency','Exchange rate','Total amount',
    'Paid by [payment_name]',
    'Invoice','Table reservation','Marketing','SMS','Delivery Management',
    'Mobile Merchant','Redeem thresholds','User Reward Points','Enabled Loyalty Points',
    'Earn Points','Manage the way customer earn points.','Rule based','Redeeming Points','Set the value of points redeemed for a discount.',
    'Enabled thresholds','if enabled this will use redeem thresholds','Points earned per each {amount} spent',
    'Minimum spent ({currency_code}) to get points','Maximum spent ({currency_code}) to get points',
    'Points the customer needs to get {amount}','Redemption policy','Cost covered by',
    'Redemption Type','Description',
    'Universal Redemption','customers can use the loyalty points earned from one merchant to redeem rewards or discounts at any participating merchant.',
    'Merchant-Specific Redemption',
    "customers can only redeem the points they earned within the same merchant's ecosystem. The loyalty points earned from one merchant cannot be used or transferred to other merchants or businesses.",
    'Global Points','Points the customer gets for register an account','Points writing additional reviews',
    'Points placing first order','Points the customer will get for booking table','Expiration','Redeeming value',
    'User Reward Points','All Points Transactions','Addon manager',
    'Minimum Redemption Points','Maximum Redemption Points','Points for Registration',
    'Points for Review','Points for first order','Points for Booking','Sub total','Cart total',
    'Food item','Universal Redemption','Merchant-Specific Redemption','Website Owner Covers the Points Cost',
    'Merchant Covers the Points Cost','Expire at the end of the next year after you earned them',
    'Expire at the end of the year from registration','Never expired','Invoice No#','Invoice Date','Due Date',
    'AMOUNT DUE','BILL TO','Description','Total','Sub total','TOTAL','Amount paid',
    'AMOUNT DUE','Quick management of the last {{limit}} orders',
    'Member since {{date_created}}','{{total_sold}} orders','This month you got {{count}} New Reviews',
    '{{sold}} sold','Payment by {{payment_name}}',
    'This is an xml Sitemap generated, mean to be consume by search engines like Google or bing.',
    'You can find more information on XML sitemaps at sitemaps.org',
    'Your sitemap URL', 'XML Sitemap',
    'Last Modified. [date_modified]','SKU#[sku]','Map view','All Groups','Map','Search Orders','Search Drivers','List',
    'Filter by zone','Filter by Groups','No available drivers','Clear filter',
    'Date from: {start} to {end}','{payment_code} {transaction_type} Sales','Tax','Tips','Total',
    'Table Booking','Shifts','Room','Tables','Campaigns','POS','Create Order','Order History','Daily Sales Report',
    'Hold','Table','Request','Search customer name','No items added','Customer','Promo','Discount','Tips','Points','Skip Kitchen',
    'Kitchen','Proceed to pay','Reset','Hold Bill','Total',
    'Close','No available Rooms and Tables','Click here to create','No available data','Available','Ordered','Occupied','Waiting for bill',
    'Hold Orders','Open Orders','Search for','Sorry, no product matched for your search. Please try again','No available Rooms and Tables',
    'Click here to create','No available Food items','Enter Promo code','Discount','Tips','Apply Total Manually','Please enter guest number',
    'Payment',"Go paperless and green, send receipt to customer's email or whatsApp",'Search customer name','No results',
    'Customer Request','Order Reference','Delivery Address','Date/Time','Include utensils','Yes','No','Payment','Web Print','Status','Close',
    'Apply Filters','Filters','Order Type','Select Order Type','Available',
    'Submit','Search food','Date','Time','Save','Delete','Clear','Enter Email Address','Invalid email format',
    'Send','WhatsApp number with country code','Invalid mobile number format','Print Web','Print Thermal','Clear all items',
    'are you sure?','Cancel','Confirm','Searching...','No results','Walk-in Customer','This field is required','Available',
    'Ordered','Occupied','Waiting for bill','Please enter guest number','Create Payment','Total Due','Pay Left','Change',
    'Date','Receive amount','Invalid number','Order status','Payment Method','Guest','Room Name','Table Name','Payment Reference number',
    'Add order notes','Customize your Order','Cooking Reference','Required','Optional','Ingredients','Select 1','Select minimum','to maximum',
    'Choose up to','Select minimum','Choose up to','Special Instructions','If sold out','Total Price','Not for sale','Add',
    'Total Price','Not for sale','Customize your Order','Cooking Reference','Required','Optional','Ingredients','Select 1','Select minimum',
    'to maximum','Choose up to','Select minimum','Choose up to','Special Instructions','If sold out','Total Price','Not for sale',
    'Add','Total Price','Not for sale','Delivery address is required','Table number is required','Please select customer',   
    "Processing...","please don't close this window",'Enter your location or select on the map','Payment Processing.','Confirm deletion',
    'Are you sure you want to delete this order? This action cannot be undone. Sent orders to kitchen will also be canceled.',
    'Yes','Cancel','Deleting records','Printing....','WebSocket error occurred, but no detailed ErrorEvent is available.',
    'View','Clear notifications','Clear all items','are you sure?','Confirm','This table is not available','Sending orders to kitchen',
    'Unable to Pay since the cart containes new item(s) that has not been sent to the kitchen',
    'Click to continue and clear new item(s)','Clearing new items','Customer','Search Order','ORDER ID','ORDER TYPE','CUSTOMER','AMOUNT','DATE','STATUS',
    'More Order Details','Total Amount','Balance','Change','Receive Amount','Add more information about this payment','Payment Reference number',
    'Add order notes','No notifications yet',"When you get notifications, they'll show up here",'Hold Order',
    'The current order will be set on hold. You can retrieve this order from the pending tabs',
    'Providing a reference to it might help you to identify the order more quickly','Notification','Clear all',
    'Item','Qty','Status','pending','Completed','Sending receipt....','Records per page','of',
    'Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec','First name','Last name',
    'Delivery address','Enter your street and house number','Street name','Street number','Aparment, suite or floor',
    'Delivery options','Add delivery instructions','eg. ring the bell after dropoff, leave next to the porch, call upon arrival, etc',
    'Address label','Save Address','Select address','Add new address','Reference','Payment','Item list',
    'Download sample template','click here','Import File','Excel File Parameters','Notice: If your food item has multiple sizes, you need to add it as two rows with the same item ID.',
    'Field Name','Item ID','The id of food item','Item Name','The food item name','Short Description','Item short description',
    'Long Description','Item long description','Size ID','Size id','Size Name','Size name','Price','Cost Price','Item cost price',
    'Discount Type','Discount type possible value fixed or percentage','Discount','Discount value must be numeric example 1.00',
    'Discount Start','Discount start date must be in correct format YYYY-mm-dd','Discount End',
    'Discount end date msut be in correct format YYYY-mm-dd example 2024-06-21','Category ID','Category Name','Category name',
    'Featured Image','Image filename, supported type png,jpg and webp','Upload the images in your server in the folder /upload/1 where in 1 = is the merchant id',
    'Featured','If food is featured must separated by comma, possible values are new,trending,best_seller,recommended',
    'Example new,trending','Status','Food item status possible value are draft,pending and publish','Discount end date must be in correct format YYYY-mm-dd',
    'example 2024-06-21','Bulk Import','Upload Bulk','The results could not be loaded.','Loading more results','Remove all items',
    'Remove item','Search','Today','Yesterday','Last 7 Days','Last 30 Days','This Month','Last Month','Custom Range',
    'Su','Mo','Tu','We','Th','Fr','Sa','January','February','March','April','May','June','July','August','September',
    'October','November','December','Search Side Bar','Duplicate Item','Duplicate','Are you sure you want to duplicate this food item?',
    'WebSocket is not open. Ready state is:','Continue','ORDER TYPE',
    'CUSTOMER','AMOUNT','DATE','STATUS','Item','Qty','Status','Records per page','of','days','Merchant Information','Banner','SMS',
    'Sms Notify Number','Enabled Order SMS Verification','Request code in minutes default is 5mins',
    'SMS BroadCast','Address','Enabled language (Single app only)','Tip Type','Enabled Tips on the following transaction',
    'Set Your Time Zone','Regular Menu Hours','These are the hours your store is available','Edit','Meta Description',
    'Notice : this section need to be fill only if you have single website restaurant','Social URL Page','reCAPTCHA v2',
    'Geolocation-db Access Key','This features will get your customer default locations in the app','signup to get your api key in',
    'Enabled Continues alert for new order','Enabled Continues alert for tableside ordering',
    'Menu options for single app addon only','Addons use checkbox','Menu options','Open in new window','Open in a pop up',
    'Merchant Page Privacy Policy','Merchant Page Terms','Merchant Page Aboutus','Mobile Page','Online Services',
    'If empty will use online services instead','Online Services','Tableside Services','Tableside Ordering','Kitchen App','Ordering & Food',
    'API Access','Mobile Settings','Push notifications','GDPR cookie consent','Javascript API','Static API','Distance Matrix',
    'Geocoder','Geosuggest','Language','Click here for language code supported','Enabled detect address','Default Map Location',
    'Address Format Options','Basic address format','street number and street name fields','street number,street name,entrance,floor,door and company fields',
    'Extended address format','User default avatar','Signup Method','Complete signup form','Phone number signup','Guest Checkout',
    'Login Method','Login using username and password','Login using OTP','Password Reset Options','Choose the method for password reset verification',
    'Email Only','SMS Only','Both SMS and Email','Complete Registration','Mask Phone format','Enabled review','Enabled edit/delete review',
    'Enabled reminder','24 hour time format','Enabled Include utensils and condoments','Auto-accepted order status',
    'Auto-accept order timer','Orders are automatically accepted after a certain number of minutes have passed since they were placed or chosen',
    'Need also to Enabled Auto-accepted order in merchant settings','Food menu layout','Food category position',
    'Left','Top','Disabled inline add to cart','Food default avatar','Enabled allow login after registration','Merchant default avatar',
    'for commission type only','Merchant default avatar','Merchant Default opening hours','when creating new merchant will copy this opening hours',
    'Merchant Default payment settings','when creating new merchant this will enabled payment gateway',
    'Email and Mobile number who will receive notifications for new,cancel order and invoice.',
    'We would like to bring to your attention that this service is not recommended for lower hosting plans',
    'The reason being that it frequently sends requests to your server, which may lead to performance issues and strain on your hosting resources',
    'To ensure a smooth and reliable experience, we highly recommend opting for a hosting plan that can handle the increased server requests without compromising the overall performance of your website or application',
    'minimum is 30 seconds','Alert Interval in seconds','Enabled Contact Us','Enabled Captcha','Contact Us Template','Your contact page url',
    'Mobile API URL','Mobile API Keys','Below is mobile app api keys that you need to set in your mobile app configurations','Delete Keys',
    'Privacy Policy','About us','Mobile Domain URL','Auto Redirect to PWA url when using device','Menu addons use checkbox',
    'Menu category use slide','Your PWA Domain URL','Your Android Google play URL','Your iOS Apps Store URL','Mobile Version',
    'Your android latest version','Your iOS latest version','example 1.0','Service account JSON file','Current Uploaded File',
    'Important! Use one service account json file for all apps','Enabled cookie consent','Show Preferences Menu',
    'Theme & Colors','Theme mode','Primary Color','Dark Color','Light Color','Position & Width','Display Position','Cookie Expiration',
    'Textual Changes','Accept Button Label','Reject Button Label','Image resizing','Runactions','Enabled runactions',
    'Test Runactions','Runactions Test Template','Kicthen App','Status (Send to Kitchen)',"When the status is set to (e.g., 'Accepted'), the order will automatically be sent to the kitchen for preparation",
    'Status (Kitchen Auto print)',"When this status is selected (e.g., 'Accepted'), the order will automatically be printed in the kitchen, initiating the preparation process without requiring manual printing by the staff",
    'Page','Enabled Multi Currency','Exchange rate provider','Manual - enter the rates manually','Automatically - take rates from provider',
    'Free Currency API','API Keys','get your api key','Cron link','below are the cron jobs that needed to run in your cpanel as http cron',
    'run end of the day','Checkout currency','Hide payment gateway for specific currencies','Gateways hidden for user that pay in {currency_description}',
    'Checkout currencies','Force to a specific currency during payment','Clear Cache','Review List','Email Subscribers','All printers',
    'Printer logs','Printer List','Select Printer Connectivity','Printer name','Auto print','User','Ukey','Sn','Add Printer',
    'Printer I.P address','Printer Port','Default printer port: 9100','Paper Width','Choose Printing Type',
    'Choose an image if you are printing a receipt in a non-English language (e.g., Arabic, Korean, Japanese) on a thermal printer',
    'Select the Character Code',"Select the Character Code only if the Printing Type is set to 'image'",
    'ID','Printer','Job Id','Delete past 30 days records','Print logs','Print Logs','Print preview','Update','process','Table name','Min Covers',
    'Max Covers','Generate Table','Add Table','Table list','Add Table','Min Covers','Max Covers','Table Order Status','Number of tables',
    'Room list','Room ID','Capacity','Total tables','Add Room','Reservation summary','Upcoming','Denied','Cancelled','No show','Wait List',
    'Add Booking','Reservation Details','Customer Details','Edit Reservation','Overview','Reservation','Notice','Each item ID must be unique. If an item ID already exists, it will not be saved',
    'Item IDs should start with {last_id}','Category ID should start with {cat_id}, and size id with {size_id}','Category IDs and Size IDs must also be unique',
    'Ticket','Firebase Configuration','Whatsapp Configuration','Enabled WhatsApp','Business Account ID','Phone number ID','Token','Update Templates',
    'Whatsapp Receipt Template','Template Variables','Customer name','Restaurant name','Order ID','Total Amount of order','Delivery Address','Restaurant Contact number',
    'Firestore Database configuration','API Key','Auth domain','Project Id','Storage Bucket','Messaging SenderId','App Id',
    'Cashout list','Collect cash','Driver list','Car registration','Groups','Employee Schedule','Map View','Shifts Schedule',
    'Driver Earnings','Driver wallet','SEO Setup','XML Sitemap','Installed addon','Available addon','Install/Update Addon','install/update',
    'Automated Status Updates','allow you to define actions that automatically change the status of an order after a certain amount of time.',
    "For example, you can set an order to be automatically accepted 10 minutes after it's placed, or mark it as delivered 1 hour after it's accepted",
    'This feature helps streamline order management by reducing manual intervention and ensuring timely updates for each order.',
    'Add Row','Update To','Time Update after (minutes)','Eg. 1 hour = 60 for 1 hour and 10 minutes = 70',
    'Map-Based Settings','Location-Based Settings','maximum of 5 country','Default Distance Unit','Get your address geolocation via service like [link] or [link2]',
    'Location Country','Location search type','sEnabled get coordinates from maps','if enabled you need to put your map api keys',
    'Map-Based Address Search','Location-Based Service Search','Delivery Fee Management','Time Estimates Management','Fee Management',
    'Add Rate','ID','Area','Fee','Please enter a keyword','State/Region','City','Distric/Area/neighborhood','Delivery Fee','Minimum Order',
    'Maximum Order','Min. Order for Free Delivery','Please select','Estimations','Add Estimation','Select Services','In Minutes','Min. Estimation Time',
    'In Minutes','Max Estimation Time','Small Order Fee','Minimum Order Amount','Checkout Date/Time','Number of days','default is 7 days','From Status',
    'Allow instant access upon registration (no admin approval required)','Bank Deposit Instructions for Subscription Payment','Bank Deposit Approved for Subscription',
    'Merchant Registration Approved','Subscription Payment Process','Subscription Payment Failed','Subscription Canceled',
    'You have {total} pending cron jobs to process. Please run the cron job processing script in your cPanel.','Auto login','Duplicate Merchant',
    'Process Jobs',"To run this cron job, please refer to your hosting provider's cPanel for specific instructions, as the steps may differ from the instructions provided below.",
    'Subscription Bank','Bank instructions for merchant subscriptions','run at the end of the day','run once every week','run once every month',
    'Driver APP','Plan Ahead: Set Special Hours for Holidays','Planning a holiday closure or special hours? Easily update your schedule for specific holidays or events. View and manage all holiday dates in one place.',
    'View all events','Edit availability','Schedule for upcoming events, holidays and operational changes to your sites.','Upcoming events',
    "You don't have upcoming events",'Delete','Event Name','Select date','View Events','Kitchen Workload','Low Workload','Orders Below',
    'Add (Minutes)','Medium Workload','Orders From','Orders To','Add (Minutes)','High Workload','Orders Above','Add (Minutes)',
    'Items Availability','Type a keyword','Show all pause items','No items found','Pause availability','Resume availability','Pause Item',
    "Select a time frame where {item_name} will be paused. After this time, it'll be automatically resumed.",'Hours','Days',
    'Resume on {date}','Unavailable','Item is unavailable indefinitely.','{n} item|{n} items','Auto Print','Printint receipt...','Event Name',
    'Date','Edit availability','This field is required','Select date','Close','Reason','Geolocation is not supported by your browser.','Position unavailable. Please try again.',
    'Request timed out. Please try again.','Deleting this order will rollback all associated earnings for both the admin and the merchant. This action is irreversible and may affect financial records. Are you sure you want to proceed?',
    'Total {total}','What is the reason for rejection?','Are you sure you want to mark reject all selected items?','Reject','{mins} min(s)',
    'Other','30 minutes','1 hour','2 hours','3 hours','6 hours','To the end of today','1 day','3 days','1 week','Indefinitely','Custom Time','Item name','Merchant',
    'Suggested Items','Suggest your best food items to be featured on the homepage for increased visibility and sales, admin will review and approve based on platform guidelines.',
    'Date Submitted','Add Suggested Items','approved','Activate Loyalty Points System','Featured Items','ID','Name','Merchant','Category','Price','Featured',
    'Priority','View Featured','Photo','Filter by','Banner List','Push notification','Approve','Item with ID#{id} has been approved','Items selected succesfully updated',
    'Body','Successfully Deleted','Please select items','Create Banner','Banner Type','Recommended image size is (1400x600)','Select Cuisine','Coordinates',
    'If coordinates is not set, this banner will shown to all locations.','Publish','Radius','Manage Order','Issue Refund','Send Kitchen','Manage Refund',
    'Refund Type','Order Amount','Amount should not exceed','Payment Type','Please Select','Reason','Full Refund','Partial Refund','Manage order','Please select status',
    'Threshold for late orders (Accepting)',"The maximum time a restaurant or merchant has to accept an order before it's considered late",'Threshold for Cancellation (Accepting)',
    "the time limit after which an order is considered extremely delayed, allowing the customer to cancel the order directly from the customer tracking page. Once the order exceeds this threshold, a 'Cancel Order' button will appear, enabling the customer to cancel the order due to excessive lateness.",
    "Late Delivery Threshold","Defines the maximum time (in minutes) after the estimated delivery time that the delivery is considered late. If the order exceeds this time, it will be flagged as delayed.",
    "Cancellation Threshold for Late Delivery","Sets the time (in minutes) after which customers will be offered the option to cancel their order due to a delayed delivery. Once the delivery exceeds this threshold, the option to cancel will be presented to the customer.",
    "In minutes",'Orders as of today {{date}}','Orders completed as of today [date]','Orders scheduled as of today [date]','Online booking T&C (optional)',
    '{{sold}} sold','{{total_sold}} sold','Recommended image size: 600x600 pixels.','Recommended image size: 1400x600 pixels.','change status by {{user}}',
    'Zone','Date','Pick a date','Time start','Select time','Time ends','Select Driver','Select Car','Instructions','Add instructions to driver',
    'Flexible','Pricing','for Every','Restaurant','Transparent pricing. No hidden costs. Advanced features to elevate your business.',
    "You don't have current subscriptions",'Subscribe','Current Plan','Item Limit','Credits Used','Order Limit','Credits Used','Running out of credits too soon?',
    'Upgrade to our more featured plan for more credits and benefits.','Your subscription has been cancelled.','Your subscription expired.','Upgrade Plan',
    'Cancel Subscription','Renew Plan','Upgrade Plan','Plan','Billing Price','Billing Cycle','Created At','Expiration','Next Due on',
    'Plan Name','Amount','Start Date','End Date','Payment','Status','Pay Now','Max Order','Unlimited','Max Product','Choose Plan','Subscriptions',
    'Subscription History','Current Subscription',"Hello! You've got a new message from {first_name}","You have new suggested feature items submitted by {restaurant_name}",
    'Customer name','Delivery Date','Driver','Rating','Orders List','Search Orders','All Filters','Notifications','Clear all','No Data Available','View all',
    'Invoice number','Period','Payment information','The balance will be taken from your account after your invoice generated.','Sincerely','Commission','Commission Rate',
    'Commission Amount','Commission + Tax','Service Fee','Tax Service Fee'
];